phraseapp:
  project_id: d86edfe2db98e1c342853a7854ba9515
  push:
    sources:
    - file: ./locales/<locale_name>.yml
      params:
        file_format: yml
  pull:
    targets:
    - file: ./locales/de.yml
      params:
        file_format: yml
        locale_id: de

