phraseapp:
  project_id: 7acb8f1a8bd4c3396cd90870477c1bb9
  push:
    sources:
    - file: ./locales/<locale_name>.yml
      params:
        file_format: yml
        update_translations: true
  pull:
    targets:
    - file: ./locales/de.yml
      params:
        file_format: yml
        locale_id: de
    - file: ./locales/admin/<locale_code>.yml
      params:
        file_format: yml
        include_empty_translations: true
