phraseapp:
  access_token: 123456
  project_id: f570afb6c855f5724f2f5186d4992deb
  file_format: yml
  push:
    sources:
    - file: ./locales/<locale_name>.yml
      params:
        file_format: yml
  pull:
    targets:
    - file: ./locales/<locale_name>.yml
      params:
        file_format: yml
