phraseapp:
  project_id: f570afb6c855f5724f2f5186d4992deb
  push:
    sources:
    - file: ./locales/<locale_name>.yml
      params:
        file_format: yml
  pull:
    targets:
    - file: ./locales/<locale_name>.yml
      params:
        file_format: yml

