phraseapp:
  project_id: 5ddb7ff823e476bcc95853e91e63e15d
  push:
    sources:
    - file: ./locales/de.json
      params:
        file_format: json
        locale_id: 8359beb77721e56dfe45117bd38605f9
  pull:
    targets:
    - file: ./locales/<locale_name>.json
      params:
        file_format: json

